// generated by stringer -type=Id; DO NOT EDIT

package biome

import "fmt"

const (
	_Id_name_0 = "OceanPlainsDesertExtremeHillsForestTaigaSwamplandRiverHellTheEndFrozenOceanFrozenRiverIcePlainsIceMountainsMushroomIslandMushroomIslandShoreBeachDesertHillsForestHillsTaigaHillsExtremeHillsEdgeJungleJungleHillsJungleEdgeDeepOceanStoneBeachColdBeachBirchForestBirchForestHillsRoofedForestColdTaigaColdTaigaHillsMegaTaigaMegaTaigaHillsExtremeHillsPlusSavannaSavannaPlateauMesaMesaPlateauFMesaPlateau"
	_Id_name_1 = "SunflowerPlainsDesertMExtremeHillsMFlowerForestTaigaMSwamplandM"
	_Id_name_2 = "IcePlainsSpikes"
	_Id_name_3 = "JungleM"
	_Id_name_4 = "JungleEdgeM"
	_Id_name_5 = "BirchForestMBirchForestHillsMRoofedForestMColdTaigaM"
	_Id_name_6 = "MegaSpruceTaigaRedwoodTaigaHillsMExtremeHillsPlusMSavannaMSavannaPlateauMMesaBryceMesaPlateauFMMesaPlateauM"
)

var (
	_Id_index_0 = [...]uint16{5, 11, 17, 29, 35, 40, 49, 54, 58, 64, 75, 86, 95, 107, 121, 140, 145, 156, 167, 177, 193, 199, 210, 220, 229, 239, 248, 259, 275, 287, 296, 310, 319, 333, 349, 356, 370, 374, 386, 397}
	_Id_index_1 = [...]uint8{15, 22, 35, 47, 53, 63}
	_Id_index_2 = [...]uint8{15}
	_Id_index_3 = [...]uint8{7}
	_Id_index_4 = [...]uint8{11}
	_Id_index_5 = [...]uint8{12, 29, 42, 52}
	_Id_index_6 = [...]uint8{15, 33, 50, 58, 73, 82, 95, 107}
)

func (i Id) String() string {
	switch {
	case 0 <= i && i <= 39:
		lo := uint16(0)
		if i > 0 {
			lo = _Id_index_0[i-1]
		}
		return _Id_name_0[lo:_Id_index_0[i]]
	case 129 <= i && i <= 134:
		i -= 129
		lo := uint8(0)
		if i > 0 {
			lo = _Id_index_1[i-1]
		}
		return _Id_name_1[lo:_Id_index_1[i]]
	case i == 140:
		return _Id_name_2
	case i == 149:
		return _Id_name_3
	case i == 151:
		return _Id_name_4
	case 155 <= i && i <= 158:
		i -= 155
		lo := uint8(0)
		if i > 0 {
			lo = _Id_index_5[i-1]
		}
		return _Id_name_5[lo:_Id_index_5[i]]
	case 160 <= i && i <= 167:
		i -= 160
		lo := uint8(0)
		if i > 0 {
			lo = _Id_index_6[i-1]
		}
		return _Id_name_6[lo:_Id_index_6[i]]
	default:
		return fmt.Sprintf("Id(%d)", i)
	}
}
