// generated by stringer -type=GameMode,Difficulty -output=level_string.go; DO NOT EDIT

package anvil

import "fmt"

const _GameMode_name = "SurvivalCreativeAdventureSpectator"

var _GameMode_index = [...]uint8{8, 16, 25, 34}

func (i GameMode) String() string {
	if i >= GameMode(len(_GameMode_index)) {
		return fmt.Sprintf("GameMode(%d)", i)
	}
	hi := _GameMode_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _GameMode_index[i-1]
	}
	return _GameMode_name[lo:hi]
}

const _Difficulty_name = "PeacefulEasyNormalHard"

var _Difficulty_index = [...]uint8{8, 12, 18, 22}

func (i Difficulty) String() string {
	if i >= Difficulty(len(_Difficulty_index)) {
		return fmt.Sprintf("Difficulty(%d)", i)
	}
	hi := _Difficulty_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _Difficulty_index[i-1]
	}
	return _Difficulty_name[lo:hi]
}
