// This file is subject to a 1-clause BSD license.
// Its contents can be found in the enclosed LICENSE file.

package recipe

import (
	"bytes"
	"fmt"
	"io"
	"math"

	"github.com/jteeuwen/mctools/anvil/item"
)

// Ingredient defines a single recipe ingredient. It holds an item id
// and the number of times it needs to be provided.
type Ingredient struct {
	Item  item.Id
	Count int
}

// Recipe defines a single recipe, optionally with a tree of sub-recipes
// needed to create its ingredients.
//
// Any item with zero ingredients can only be mined or farmed.
//
// Multiple recipes for the same target item can be created, if it can
// be crafted with different sets of ingredients.
type Recipe struct {
	Ingredients []Ingredient // List of ingredients for this recipe.
	Item        item.Id      // The item that will be created from this recipe.
	Count       int          // The number of items that will be produced.
}

// Find returns all recipes which craft the given item.
//
// Returns nil if no recipes exist for this item.
func Find(id item.Id) RecipeList {
	set := make(RecipeList, 0, 2)

	for _, r := range recipes {
		if r.Item == id {
			set = append(set, r)
		}
	}

	if len(set) == 0 {
		set = append(set, new(id, 1))
	}

	return set
}

func (r *Recipe) String() string {
	var w bytes.Buffer
	var s []item.Id
	r.dump(&s, &w, 1, "")
	return w.String()
}

// dump writes to w a human readable dump of the recipe tree.
//
// We retain a stack of visited recipe item ids, because some recipes
// define cyclic dependencies on each other. We need to break out of that
// loop here by ensuring we only process each recipe/item once.
func (r *Recipe) dump(stack *[]item.Id, w io.Writer, count int, indent string) {
	fmt.Fprintf(w, "%s%d x %s\n", indent, count, r.Item)

	if hasItem(*stack, r.Item) {
		return
	}
	*stack = append(*stack, r.Item)
	sz := len(*stack)

	count = int(math.Ceil(float64(count) / float64(r.Count)))

	for _, i := range r.Ingredients {
		st := (*stack)[:sz:sz]
		set := Find(i.Item)
		set[0].dump(&st, w, i.Count*count, indent+"  ")
	}
}

// hasItem returns true if set contains v
func hasItem(set []item.Id, v item.Id) bool {
	for _, id := range set {
		if id == v {
			return true
		}
	}
	return false
}

// new creates a new recipe for the given id and count and
// optional list of ingredients.
func new(item item.Id, count int, ingredients ...Ingredient) *Recipe {
	if count <= 0 {
		count = 1
	}

	return &Recipe{
		Item:        item,
		Count:       count,
		Ingredients: ingredients,
	}
}

// recipes defines a global set of existing crafting and smelting recipes.
//
// There may be multiple recipes for the same item. An example of this
// is a Wooden Stick. They can be crafted from various different wood plank
// types. Each version counts as a unique recipe.
//
// Ingredient represents a single ingredient for a crafting recipe. This
// contains the id and the number of items required.
var recipes = []*Recipe{
	// Smelting/Mining
	new(item.PorkchopCooked, 1, Ingredient{item.PorkchopRaw, 1}),
	new(item.Steak, 1, Ingredient{item.BeefRaw, 1}),
	new(item.ChickenCooked, 1, Ingredient{item.ChickenRaw, 1}),
	new(item.FishCooked, 1, Ingredient{item.FishRaw, 1}),
	new(item.SalmonCooked, 1, Ingredient{item.SalmonRaw, 1}),
	new(item.PotatoBaked, 1, Ingredient{item.Potato, 1}),
	new(item.MuttonCooked, 1, Ingredient{item.MuttonRaw, 1}),
	new(item.RabbitCooked, 1, Ingredient{item.RabbitRaw, 1}),
	new(item.IronIngot, 1, Ingredient{item.IronOre, 1}),
	new(item.GoldIngot, 1, Ingredient{item.GoldOre, 1}),
	new(item.Glass, 1, Ingredient{item.Sand, 1}),
	new(item.Cobblestone, 1, Ingredient{item.Stone, 1}),
	new(item.ClayBrick, 1, Ingredient{item.Clay, 1}),
	new(item.NetherBrick, 1, Ingredient{item.Netherrack, 1}),
	new(item.HardenedClay, 1, Ingredient{item.ClayBlock, 1}),
	new(item.StoneBrickCracked, 1, Ingredient{item.StoneBrick, 1}),
	new(item.Diamond, 3, Ingredient{item.DiamondOre, 1}),
	new(item.LapisLazuli, 4, Ingredient{item.LapisLazuliOre, 1}),
	new(item.RedstoneWire, 4, Ingredient{item.RedstoneOre, 1}),
	new(item.Coal, 1, Ingredient{item.CoalOre, 1}),
	new(item.Emerald, 1, Ingredient{item.EmeraldOre, 1}),
	new(item.NetherQuartz, 1, Ingredient{item.NetherQuartzOre, 1}),
	new(item.Charcoal, 1, Ingredient{item.OakLog, 1}),
	new(item.Charcoal, 1, Ingredient{item.BirchLog, 1}),
	new(item.Charcoal, 1, Ingredient{item.SpruceLog, 1}),
	new(item.Charcoal, 1, Ingredient{item.JungleLog, 1}),
	new(item.Charcoal, 1, Ingredient{item.AcaciaLog, 1}),
	new(item.Charcoal, 1, Ingredient{item.DarkOakLog, 1}),
	new(item.GreenDye, 1, Ingredient{item.Cactus, 1}),
	new(item.SpongeWet, 1, Ingredient{item.Sponge, 1}),

	// Crafting
	new(item.Andesite, 2,
		Ingredient{item.Diorite, 1},
		Ingredient{item.Cobblestone, 1},
	),
	new(item.AndesitePolished, 4, Ingredient{item.Andesite, 4}),
	new(item.CoalBlock, 1, Ingredient{item.Coal, 9}),
	new(item.DiamondBlock, 1, Ingredient{item.Diamond, 9}),
	new(item.EmeraldBlock, 1, Ingredient{item.Emerald, 9}),
	new(item.GoldBlock, 1, Ingredient{item.GoldIngot, 9}),
	new(item.IronBlock, 1, Ingredient{item.IronIngot, 9}),
	new(item.Bookshelf, 1,
		Ingredient{item.OakPlanks, 6},
		Ingredient{item.Book, 3},
	),
	new(item.Bookshelf, 1,
		Ingredient{item.SprucePlanks, 6},
		Ingredient{item.Book, 3},
	),
	new(item.Bookshelf, 1,
		Ingredient{item.BirchPlanks, 6},
		Ingredient{item.Book, 3},
	),
	new(item.Bookshelf, 1,
		Ingredient{item.JunglePlanks, 6},
		Ingredient{item.Book, 3},
	),
	new(item.Bookshelf, 1,
		Ingredient{item.AcaciaPlanks, 6},
		Ingredient{item.Book, 3},
	),
	new(item.Bookshelf, 1,
		Ingredient{item.DarkOakPlanks, 6},
		Ingredient{item.Book, 3},
	),
	new(item.Brick, 1, Ingredient{item.ClayBrick, 4}),
	new(item.ClayBlock, 1, Ingredient{item.Clay, 4}),
	new(item.CobblestoneWall, 6, Ingredient{item.Cobblestone, 6}),
	new(item.PrismarineDark, 1,
		Ingredient{item.PrismarineShard, 8},
		Ingredient{item.InkSac, 1},
	),
	new(item.Diorite, 2,
		Ingredient{item.Cobblestone, 2},
		Ingredient{item.NetherQuartz, 2},
	),
	new(item.DioritePolished, 4, Ingredient{item.Diorite, 4}),
	new(item.JackOLantern, 1,
		Ingredient{item.Pumpkin, 1},
		Ingredient{item.Torch, 1},
	),
	new(item.LapisLazuliBlock, 1, Ingredient{item.LapisLazuli, 9}),
	new(item.MossStone, 1,
		Ingredient{item.Cobblestone, 1},
		Ingredient{item.Vines, 1},
	),
	new(item.PrismarineBricks, 1, Ingredient{item.PrismarineShard, 9}),
	new(item.Sandstone, 1, Ingredient{item.Sand, 4}),
	new(item.SandstoneSmooth, 4, Ingredient{item.Sandstone, 4}),
	new(item.SandstoneChiseled, 1, Ingredient{item.SandstoneSlab, 2}),
	new(item.StoneSlab, 6, Ingredient{item.Stone, 3}),
	new(item.SandstoneSlab, 6, Ingredient{item.Sandstone, 3}),
	new(item.SandstoneSlab, 6, Ingredient{item.SandstoneSmooth, 3}),
	new(item.CobblestoneSlab, 6, Ingredient{item.Cobblestone, 3}),
	new(item.BrickSlab, 6, Ingredient{item.Brick, 3}),
	new(item.StoneBrickSlab, 6, Ingredient{item.StoneBrick, 3}),
	new(item.StoneBrickSlab, 6, Ingredient{item.StoneBrickCracked, 3}),
	new(item.StoneBrickSlab, 6, Ingredient{item.StoneBrickChiseled, 3}),
	new(item.OakSlab, 6, Ingredient{item.OakPlanks, 3}),
	new(item.SpruceSlab, 6, Ingredient{item.SprucePlanks, 3}),
	new(item.BirchSlab, 6, Ingredient{item.BirchPlanks, 3}),
	new(item.JungleSlab, 6, Ingredient{item.JunglePlanks, 3}),
	new(item.AcaciaSlab, 6, Ingredient{item.AcaciaPlanks, 3}),
	new(item.DarkOakSlab, 6, Ingredient{item.DarkOakPlanks, 3}),
	new(item.NetherBrickSlab, 6, Ingredient{item.NetherBrickBlock, 3}),
	new(item.QuartzSlab, 6, Ingredient{item.QuartzBlock, 3}),
	new(item.QuartzSlab, 6, Ingredient{item.QuartzBlockPillar, 3}),
	new(item.QuartzSlab, 6, Ingredient{item.QuartzBlockChiseled, 3}),
	new(item.RedSandstoneSlab, 6, Ingredient{item.RedSandstone, 3}),
	new(item.RedSandstoneSlab, 6, Ingredient{item.RedSandstoneSmooth, 3}),
	new(item.RedSandstoneSlab, 6, Ingredient{item.RedSandstoneChiseled, 3}),
	new(item.WhiteStainedGlass, 8,
		Ingredient{item.Glass, 8},
		Ingredient{item.Bonemeal, 1},
	),
	new(item.OrangeStainedGlass, 8,
		Ingredient{item.Glass, 8},
		Ingredient{item.OrangeDye, 1},
	),
	new(item.MagentaStainedGlass, 8,
		Ingredient{item.Glass, 8},
		Ingredient{item.MagentaDye, 1},
	),
	new(item.LightBlueStainedGlass, 8,
		Ingredient{item.Glass, 8},
		Ingredient{item.LightBlueDye, 1},
	),
	new(item.YellowStainedGlass, 8,
		Ingredient{item.Glass, 8},
		Ingredient{item.YellowDye, 1},
	),
	new(item.LimeStainedGlass, 8,
		Ingredient{item.Glass, 8},
		Ingredient{item.LimeDye, 1},
	),
	new(item.PinkStainedGlass, 8,
		Ingredient{item.Glass, 8},
		Ingredient{item.PinkDye, 1},
	),
	new(item.GrayStainedGlass, 8,
		Ingredient{item.Glass, 8},
		Ingredient{item.GrayDye, 1},
	),
	new(item.LightGrayStainedGlass, 8,
		Ingredient{item.Glass, 8},
		Ingredient{item.LightGrayDye, 1},
	),
	new(item.CyanStainedGlass, 8,
		Ingredient{item.Glass, 8},
		Ingredient{item.CyanDye, 1},
	),
	new(item.PurpleStainedGlass, 8,
		Ingredient{item.Glass, 8},
		Ingredient{item.PurpleDye, 1},
	),
	new(item.BlueStainedGlass, 8,
		Ingredient{item.Glass, 8},
		Ingredient{item.LapisLazuli, 1},
	),
	new(item.BrownStainedGlass, 8,
		Ingredient{item.Glass, 8},
		Ingredient{item.CocoaBean, 1},
	),
	new(item.GreenStainedGlass, 8,
		Ingredient{item.Glass, 8},
		Ingredient{item.GreenDye, 1},
	),
	new(item.RedStainedGlass, 8,
		Ingredient{item.Glass, 8},
		Ingredient{item.RedDye, 1},
	),
	new(item.BlackStainedGlass, 8,
		Ingredient{item.Glass, 8},
		Ingredient{item.InkSac, 1},
	),
	new(item.OakStairs, 4, Ingredient{item.OakPlanks, 6}),
	new(item.BirchStairs, 4, Ingredient{item.BirchPlanks, 6}),
	new(item.SpruceStairs, 4, Ingredient{item.SprucePlanks, 6}),
	new(item.JungleStairs, 4, Ingredient{item.JunglePlanks, 6}),
	new(item.AcaciaStairs, 4, Ingredient{item.AcaciaPlanks, 6}),
	new(item.DarkOakStairs, 4, Ingredient{item.DarkOakPlanks, 6}),
	new(item.CobblestoneStairs, 4, Ingredient{item.Cobblestone, 6}),
	new(item.BrickStairs, 4, Ingredient{item.Brick, 6}),
	new(item.StoneBrickStairs, 4, Ingredient{item.StoneBrick, 6}),
	new(item.StoneBrickStairs, 4, Ingredient{item.StoneBrickChiseled, 6}),
	new(item.StoneBrickStairs, 4, Ingredient{item.StoneBrickCracked, 6}),
	new(item.StoneBrickStairs, 4, Ingredient{item.StoneBrickMossy, 6}),
	new(item.NetherBrickStairs, 4, Ingredient{item.NetherBrickBlock, 6}),
	new(item.SandstoneStairs, 4, Ingredient{item.Sandstone, 6}),
	new(item.SandstoneStairs, 4, Ingredient{item.SandstoneSmooth, 6}),
	new(item.SandstoneStairs, 4, Ingredient{item.SandstoneChiseled, 6}),
	new(item.QuartzStairs, 4, Ingredient{item.QuartzBlock, 6}),
	new(item.QuartzStairs, 4, Ingredient{item.QuartzBlockChiseled, 6}),
	new(item.QuartzStairs, 4, Ingredient{item.QuartzBlockPillar, 6}),
	new(item.RedSandstoneStairs, 4, Ingredient{item.RedSandstone, 6}),
	new(item.RedSandstoneStairs, 4, Ingredient{item.RedSandstoneChiseled, 6}),
	new(item.RedSandstoneStairs, 4, Ingredient{item.RedSandstoneSmooth, 6}),
	new(item.StoneBrick, 4, Ingredient{item.Stone, 4}),
	new(item.StoneBrickMossy, 1,
		Ingredient{item.StoneBrick, 1},
		Ingredient{item.Vines, 1},
	),
	new(item.StoneBrickChiseled, 1, Ingredient{item.StoneBrickSlab, 2}),
	new(item.WhiteStainedClay, 8,
		Ingredient{item.HardenedClay, 8},
		Ingredient{item.Bonemeal, 1},
	),
	new(item.OrangeStainedClay, 8,
		Ingredient{item.HardenedClay, 8},
		Ingredient{item.OrangeDye, 1},
	),
	new(item.MagentaStainedClay, 8,
		Ingredient{item.HardenedClay, 8},
		Ingredient{item.MagentaDye, 1},
	),
	new(item.LightBlueStainedClay, 8,
		Ingredient{item.HardenedClay, 8},
		Ingredient{item.LightBlueDye, 1},
	),
	new(item.YellowStainedClay, 8,
		Ingredient{item.HardenedClay, 8},
		Ingredient{item.YellowDye, 1},
	),
	new(item.LimeStainedClay, 8,
		Ingredient{item.HardenedClay, 8},
		Ingredient{item.LimeDye, 1},
	),
	new(item.PinkStainedClay, 8,
		Ingredient{item.HardenedClay, 8},
		Ingredient{item.PinkDye, 1},
	),
	new(item.GrayStainedClay, 8,
		Ingredient{item.HardenedClay, 8},
		Ingredient{item.GrayDye, 1},
	),
	new(item.LightGrayStainedClay, 8,
		Ingredient{item.HardenedClay, 8},
		Ingredient{item.LightGrayDye, 1},
	),
	new(item.CyanStainedClay, 8,
		Ingredient{item.HardenedClay, 8},
		Ingredient{item.CyanDye, 1},
	),
	new(item.PurpleStainedClay, 8,
		Ingredient{item.HardenedClay, 8},
		Ingredient{item.PurpleDye, 1},
	),
	new(item.BlueStainedClay, 8,
		Ingredient{item.HardenedClay, 8},
		Ingredient{item.LapisLazuli, 1},
	),
	new(item.BrownStainedClay, 8,
		Ingredient{item.HardenedClay, 8},
		Ingredient{item.CocoaBean, 1},
	),
	new(item.GreenStainedClay, 8,
		Ingredient{item.HardenedClay, 8},
		Ingredient{item.GreenDye, 1},
	),
	new(item.RedStainedClay, 8,
		Ingredient{item.HardenedClay, 8},
		Ingredient{item.RedDye, 1},
	),
	new(item.BlackStainedClay, 8,
		Ingredient{item.HardenedClay, 8},
		Ingredient{item.InkSac, 1},
	),
	new(item.EmeraldBlock, 1, Ingredient{item.Emerald, 9}),
	new(item.RedSandstone, 1, Ingredient{item.RedSand, 4}),
	new(item.RedSandstoneSmooth, 4, Ingredient{item.RedSandstone, 4}),
	new(item.RedSandstoneChiseled, 1, Ingredient{item.RedSandstoneSlab, 2}),
	new(item.SnowBlock, 1, Ingredient{item.Snowball, 4}),
	new(item.QuartzBlock, 1, Ingredient{item.NetherQuartz, 4}),
	new(item.QuartzBlockChiseled, 1, Ingredient{item.QuartzSlab, 2}),
	new(item.QuartzBlockPillar, 2, Ingredient{item.QuartzBlock, 2}),
	new(item.Glowstone, 1, Ingredient{item.GlowstoneDust, 4}),
	new(item.Granite, 1,
		Ingredient{item.Diorite, 1},
		Ingredient{item.NetherQuartz, 1},
	),
	new(item.GranitePolished, 4, Ingredient{item.Granite, 4}),
	new(item.HayBale, 1, Ingredient{item.Wheat, 9}),
	new(item.SeaLantern, 1,
		Ingredient{item.PrismarineShard, 4},
		Ingredient{item.PrismarineCrystals, 5},
	),
	new(item.OakPlanks, 4, Ingredient{item.OakLog, 1}),
	new(item.BirchPlanks, 4, Ingredient{item.BirchLog, 1}),
	new(item.SprucePlanks, 4, Ingredient{item.SpruceLog, 1}),
	new(item.JunglePlanks, 4, Ingredient{item.JungleLog, 1}),
	new(item.AcaciaPlanks, 4, Ingredient{item.AcaciaLog, 1}),
	new(item.DarkOakPlanks, 4, Ingredient{item.DarkOakLog, 1}),
	new(item.NetherBrickBlock, 1, Ingredient{item.NetherBrick, 4}),
	new(item.MelonBlock, 1, Ingredient{item.MelonSlice, 9}),
	new(item.Prismarine, 1, Ingredient{item.PrismarineShard, 4}),
	new(item.CoarseDirt, 4,
		Ingredient{item.Dirt, 2},
		Ingredient{item.Gravel, 2},
	),
	new(item.WhiteWool, 1, Ingredient{item.String, 4}),
	new(item.OrangeWool, 1,
		Ingredient{item.WhiteWool, 1},
		Ingredient{item.OrangeDye, 1},
	),
	new(item.MagentaWool, 1,
		Ingredient{item.WhiteWool, 1},
		Ingredient{item.MagentaDye, 1},
	),
	new(item.LightBlueWool, 1,
		Ingredient{item.WhiteWool, 1},
		Ingredient{item.LightBlueDye, 1},
	),
	new(item.YellowWool, 1,
		Ingredient{item.WhiteWool, 1},
		Ingredient{item.YellowDye, 1},
	),
	new(item.LimeWool, 1,
		Ingredient{item.WhiteWool, 1},
		Ingredient{item.LimeDye, 1},
	),
	new(item.PinkWool, 1,
		Ingredient{item.WhiteWool, 1},
		Ingredient{item.PinkDye, 1},
	),
	new(item.GrayWool, 1,
		Ingredient{item.WhiteWool, 1},
		Ingredient{item.GrayDye, 1},
	),
	new(item.LightGrayWool, 1,
		Ingredient{item.WhiteWool, 1},
		Ingredient{item.LightGrayDye, 1},
	),
	new(item.CyanWool, 1,
		Ingredient{item.WhiteWool, 1},
		Ingredient{item.CyanDye, 1},
	),
	new(item.PurpleWool, 1,
		Ingredient{item.WhiteWool, 1},
		Ingredient{item.PurpleDye, 1},
	),
	new(item.BlueWool, 1,
		Ingredient{item.WhiteWool, 1},
		Ingredient{item.LapisLazuli, 1},
	),
	new(item.BrownWool, 1,
		Ingredient{item.WhiteWool, 1},
		Ingredient{item.CocoaBean, 1},
	),
	new(item.GreenWool, 1,
		Ingredient{item.WhiteWool, 1},
		Ingredient{item.GreenDye, 1},
	),
	new(item.RedWool, 1,
		Ingredient{item.WhiteWool, 1},
		Ingredient{item.RedDye, 1},
	),
	new(item.BlackWool, 1,
		Ingredient{item.WhiteWool, 1},
		Ingredient{item.InkSac, 1},
	),
	new(item.Torch, 4,
		Ingredient{item.Coal, 1},
		Ingredient{item.Stick, 1},
	),
	new(item.Furnace, 1, Ingredient{item.Cobblestone, 8}),
	new(item.Ladder, 3, Ingredient{item.Stick, 7}),
	new(item.OakFence, 3,
		Ingredient{item.OakPlanks, 4},
		Ingredient{item.Stick, 2},
	),
	new(item.BirchFence, 3,
		Ingredient{item.BirchPlanks, 4},
		Ingredient{item.Stick, 2},
	),
	new(item.SpruceFence, 3,
		Ingredient{item.SprucePlanks, 4},
		Ingredient{item.Stick, 2},
	),
	new(item.JungleFence, 3,
		Ingredient{item.JunglePlanks, 4},
		Ingredient{item.Stick, 2},
	),
	new(item.AcaciaFence, 3,
		Ingredient{item.AcaciaPlanks, 4},
		Ingredient{item.Stick, 2},
	),
	new(item.DarkOakFence, 3,
		Ingredient{item.DarkOakPlanks, 4},
		Ingredient{item.Stick, 2},
	),
	new(item.NetherBrickFence, 3, Ingredient{item.NetherBrickBlock, 6}),
	new(item.GlassPane, 16, Ingredient{item.Glass, 6}),
	new(item.TrappedChest, 16,
		Ingredient{item.Chest, 1},
		Ingredient{item.TripwireHook, 1},
	),
	new(item.WhiteCarpet, 1, Ingredient{item.WhiteWool, 2}),
	new(item.OrangeCarpet, 3, Ingredient{item.OrangeWool, 2}),
	new(item.MagentaCarpet, 3, Ingredient{item.MagentaWool, 2}),
	new(item.LightBlueCarpet, 3, Ingredient{item.LightBlueWool, 2}),
	new(item.YellowCarpet, 3, Ingredient{item.YellowWool, 2}),
	new(item.LimeCarpet, 3, Ingredient{item.LimeWool, 2}),
	new(item.PinkCarpet, 3, Ingredient{item.PinkWool, 2}),
	new(item.GrayCarpet, 3, Ingredient{item.GrayWool, 2}),
	new(item.LightGrayCarpet, 3, Ingredient{item.LightGrayWool, 2}),
	new(item.CyanCarpet, 3, Ingredient{item.CyanWool, 2}),
	new(item.PurpleCarpet, 3, Ingredient{item.PurpleWool, 2}),
	new(item.BlueCarpet, 3, Ingredient{item.BlueWool, 2}),
	new(item.BrownCarpet, 3, Ingredient{item.BrownWool, 2}),
	new(item.GreenCarpet, 3, Ingredient{item.GreenWool, 2}),
	new(item.RedCarpet, 3, Ingredient{item.RedWool, 2}),
	new(item.BlackCarpet, 3, Ingredient{item.BlackWool, 2}),
	new(item.Painting, 1,
		Ingredient{item.WhiteWool, 1},
		Ingredient{item.Stick, 8},
	),
	new(item.Painting, 1,
		Ingredient{item.OrangeWool, 1},
		Ingredient{item.Stick, 8},
	),
	new(item.Painting, 1,
		Ingredient{item.MagentaWool, 1},
		Ingredient{item.Stick, 8},
	),
	new(item.Painting, 1,
		Ingredient{item.LightBlueWool, 1},
		Ingredient{item.Stick, 8},
	),
	new(item.Painting, 1,
		Ingredient{item.YellowWool, 1},
		Ingredient{item.Stick, 8},
	),
	new(item.Painting, 1,
		Ingredient{item.LimeWool, 1},
		Ingredient{item.Stick, 8},
	),
	new(item.Painting, 1,
		Ingredient{item.PinkWool, 1},
		Ingredient{item.Stick, 8},
	),
	new(item.Painting, 1,
		Ingredient{item.GrayWool, 1},
		Ingredient{item.Stick, 8},
	),
	new(item.Painting, 1,
		Ingredient{item.LightGrayWool, 1},
		Ingredient{item.Stick, 8},
	),
	new(item.Painting, 1,
		Ingredient{item.CyanWool, 1},
		Ingredient{item.Stick, 8},
	),
	new(item.Painting, 1,
		Ingredient{item.PurpleWool, 1},
		Ingredient{item.Stick, 8},
	),
	new(item.Painting, 1,
		Ingredient{item.BlueWool, 1},
		Ingredient{item.Stick, 8},
	),
	new(item.Painting, 1,
		Ingredient{item.BrownWool, 1},
		Ingredient{item.Stick, 8},
	),
	new(item.Painting, 1,
		Ingredient{item.GreenWool, 1},
		Ingredient{item.Stick, 8},
	),
	new(item.Painting, 1,
		Ingredient{item.RedWool, 1},
		Ingredient{item.Stick, 8},
	),
	new(item.Painting, 1,
		Ingredient{item.BlackWool, 1},
		Ingredient{item.Stick, 8},
	),
	new(item.Sign, 3,
		Ingredient{item.OakPlanks, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.Sign, 3,
		Ingredient{item.BirchPlanks, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.Sign, 3,
		Ingredient{item.SprucePlanks, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.Sign, 3,
		Ingredient{item.JunglePlanks, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.Sign, 3,
		Ingredient{item.AcaciaPlanks, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.Sign, 3,
		Ingredient{item.DarkOakPlanks, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.Bed, 1,
		Ingredient{item.OakPlanks, 3},
		Ingredient{item.WhiteWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.BirchPlanks, 3},
		Ingredient{item.WhiteWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.SprucePlanks, 3},
		Ingredient{item.WhiteWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.JunglePlanks, 3},
		Ingredient{item.WhiteWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.AcaciaPlanks, 3},
		Ingredient{item.WhiteWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.DarkOakPlanks, 3},
		Ingredient{item.WhiteWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.OakPlanks, 3},
		Ingredient{item.OrangeWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.BirchPlanks, 3},
		Ingredient{item.OrangeWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.SprucePlanks, 3},
		Ingredient{item.OrangeWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.JunglePlanks, 3},
		Ingredient{item.OrangeWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.AcaciaPlanks, 3},
		Ingredient{item.OrangeWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.DarkOakPlanks, 3},
		Ingredient{item.OrangeWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.OakPlanks, 3},
		Ingredient{item.MagentaWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.BirchPlanks, 3},
		Ingredient{item.MagentaWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.SprucePlanks, 3},
		Ingredient{item.MagentaWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.JunglePlanks, 3},
		Ingredient{item.MagentaWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.AcaciaPlanks, 3},
		Ingredient{item.MagentaWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.DarkOakPlanks, 3},
		Ingredient{item.MagentaWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.OakPlanks, 3},
		Ingredient{item.LightBlueWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.BirchPlanks, 3},
		Ingredient{item.LightBlueWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.SprucePlanks, 3},
		Ingredient{item.LightBlueWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.JunglePlanks, 3},
		Ingredient{item.LightBlueWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.AcaciaPlanks, 3},
		Ingredient{item.LightBlueWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.DarkOakPlanks, 3},
		Ingredient{item.LightBlueWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.OakPlanks, 3},
		Ingredient{item.YellowWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.BirchPlanks, 3},
		Ingredient{item.YellowWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.SprucePlanks, 3},
		Ingredient{item.YellowWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.JunglePlanks, 3},
		Ingredient{item.YellowWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.AcaciaPlanks, 3},
		Ingredient{item.YellowWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.DarkOakPlanks, 3},
		Ingredient{item.YellowWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.OakPlanks, 3},
		Ingredient{item.LimeWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.BirchPlanks, 3},
		Ingredient{item.LimeWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.SprucePlanks, 3},
		Ingredient{item.LimeWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.JunglePlanks, 3},
		Ingredient{item.LimeWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.AcaciaPlanks, 3},
		Ingredient{item.LimeWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.DarkOakPlanks, 3},
		Ingredient{item.LimeWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.OakPlanks, 3},
		Ingredient{item.PinkWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.BirchPlanks, 3},
		Ingredient{item.PinkWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.SprucePlanks, 3},
		Ingredient{item.PinkWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.JunglePlanks, 3},
		Ingredient{item.PinkWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.AcaciaPlanks, 3},
		Ingredient{item.PinkWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.DarkOakPlanks, 3},
		Ingredient{item.PinkWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.OakPlanks, 3},
		Ingredient{item.GrayWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.BirchPlanks, 3},
		Ingredient{item.GrayWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.SprucePlanks, 3},
		Ingredient{item.GrayWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.JunglePlanks, 3},
		Ingredient{item.GrayWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.AcaciaPlanks, 3},
		Ingredient{item.GrayWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.DarkOakPlanks, 3},
		Ingredient{item.GrayWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.OakPlanks, 3},
		Ingredient{item.LightGrayWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.BirchPlanks, 3},
		Ingredient{item.LightGrayWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.SprucePlanks, 3},
		Ingredient{item.LightGrayWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.JunglePlanks, 3},
		Ingredient{item.LightGrayWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.AcaciaPlanks, 3},
		Ingredient{item.LightGrayWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.DarkOakPlanks, 3},
		Ingredient{item.LightGrayWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.OakPlanks, 3},
		Ingredient{item.CyanWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.BirchPlanks, 3},
		Ingredient{item.CyanWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.SprucePlanks, 3},
		Ingredient{item.CyanWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.JunglePlanks, 3},
		Ingredient{item.CyanWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.AcaciaPlanks, 3},
		Ingredient{item.CyanWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.DarkOakPlanks, 3},
		Ingredient{item.CyanWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.OakPlanks, 3},
		Ingredient{item.PurpleWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.BirchPlanks, 3},
		Ingredient{item.PurpleWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.SprucePlanks, 3},
		Ingredient{item.PurpleWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.JunglePlanks, 3},
		Ingredient{item.PurpleWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.AcaciaPlanks, 3},
		Ingredient{item.PurpleWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.DarkOakPlanks, 3},
		Ingredient{item.PurpleWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.OakPlanks, 3},
		Ingredient{item.BlueWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.BirchPlanks, 3},
		Ingredient{item.BlueWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.SprucePlanks, 3},
		Ingredient{item.BlueWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.JunglePlanks, 3},
		Ingredient{item.BlueWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.AcaciaPlanks, 3},
		Ingredient{item.BlueWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.DarkOakPlanks, 3},
		Ingredient{item.BlueWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.OakPlanks, 3},
		Ingredient{item.BrownWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.BirchPlanks, 3},
		Ingredient{item.BrownWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.SprucePlanks, 3},
		Ingredient{item.BrownWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.JunglePlanks, 3},
		Ingredient{item.BrownWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.AcaciaPlanks, 3},
		Ingredient{item.BrownWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.DarkOakPlanks, 3},
		Ingredient{item.BrownWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.OakPlanks, 3},
		Ingredient{item.GreenWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.BirchPlanks, 3},
		Ingredient{item.GreenWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.SprucePlanks, 3},
		Ingredient{item.GreenWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.JunglePlanks, 3},
		Ingredient{item.GreenWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.AcaciaPlanks, 3},
		Ingredient{item.GreenWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.DarkOakPlanks, 3},
		Ingredient{item.GreenWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.OakPlanks, 3},
		Ingredient{item.RedWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.BirchPlanks, 3},
		Ingredient{item.RedWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.SprucePlanks, 3},
		Ingredient{item.RedWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.JunglePlanks, 3},
		Ingredient{item.RedWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.AcaciaPlanks, 3},
		Ingredient{item.RedWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.DarkOakPlanks, 3},
		Ingredient{item.RedWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.OakPlanks, 3},
		Ingredient{item.BlackWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.BirchPlanks, 3},
		Ingredient{item.BlackWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.SprucePlanks, 3},
		Ingredient{item.BlackWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.JunglePlanks, 3},
		Ingredient{item.BlackWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.AcaciaPlanks, 3},
		Ingredient{item.BlackWool, 3},
	),
	new(item.Bed, 1,
		Ingredient{item.DarkOakPlanks, 3},
		Ingredient{item.BlackWool, 3},
	),
	new(item.FlowerPot, 1, Ingredient{item.ClayBrick, 3}),
	new(item.WhiteBanner, 1,
		Ingredient{item.WhiteWool, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.OrangeBanner, 1,
		Ingredient{item.OrangeWool, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.MagentaBanner, 1,
		Ingredient{item.MagentaWool, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.LightBlueBanner, 1,
		Ingredient{item.LightBlueWool, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.YellowBanner, 1,
		Ingredient{item.YellowWool, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.LimeBanner, 1,
		Ingredient{item.LimeWool, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.PinkBanner, 1,
		Ingredient{item.PinkWool, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.GrayBanner, 1,
		Ingredient{item.GrayWool, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.LightGrayBanner, 1,
		Ingredient{item.LightGrayWool, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.CyanBanner, 1,
		Ingredient{item.CyanWool, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.PurpleBanner, 1,
		Ingredient{item.PurpleWool, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.BlueBanner, 1,
		Ingredient{item.BlueWool, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.BrownBanner, 1,
		Ingredient{item.BrownWool, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.GreenBanner, 1,
		Ingredient{item.GreenWool, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.RedBanner, 1,
		Ingredient{item.RedWool, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.BlackBanner, 1,
		Ingredient{item.BlackWool, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.Snow, 6, Ingredient{item.SnowBlock, 3}),
	new(item.IronBars, 16, Ingredient{item.IronIngot, 6}),
	new(item.Anvil, 1,
		Ingredient{item.IronBlock, 4},
		Ingredient{item.IronIngot, 4},
	),
	new(item.EnderChest, 1,
		Ingredient{item.Obsidian, 8},
		Ingredient{item.EyeOfEnder, 1},
	),
	new(item.Jukebox, 1,
		Ingredient{item.OakPlanks, 8},
		Ingredient{item.Diamond, 1},
	),
	new(item.Jukebox, 1,
		Ingredient{item.BirchPlanks, 8},
		Ingredient{item.Diamond, 1},
	),
	new(item.Jukebox, 1,
		Ingredient{item.SprucePlanks, 8},
		Ingredient{item.Diamond, 1},
	),
	new(item.Jukebox, 1,
		Ingredient{item.JunglePlanks, 8},
		Ingredient{item.Diamond, 1},
	),
	new(item.Jukebox, 1,
		Ingredient{item.AcaciaPlanks, 8},
		Ingredient{item.Diamond, 1},
	),
	new(item.Jukebox, 1,
		Ingredient{item.DarkOakPlanks, 8},
		Ingredient{item.Diamond, 1},
	),
	new(item.SlimeBlock, 1, Ingredient{item.Slimeball, 9}),
	new(item.EnchantmentTable, 1,
		Ingredient{item.Obsidian, 4},
		Ingredient{item.Diamond, 2},
		Ingredient{item.Book, 1},
	),
	new(item.Workbench, 1, Ingredient{item.OakPlanks, 4}),
	new(item.Workbench, 1, Ingredient{item.BirchPlanks, 4}),
	new(item.Workbench, 1, Ingredient{item.SprucePlanks, 4}),
	new(item.Workbench, 1, Ingredient{item.JunglePlanks, 4}),
	new(item.Workbench, 1, Ingredient{item.AcaciaPlanks, 4}),
	new(item.Workbench, 1, Ingredient{item.DarkOakPlanks, 4}),
	new(item.ItemFrame, 1,
		Ingredient{item.Leather, 1},
		Ingredient{item.Stick, 8},
	),
	new(item.ArmorStand, 1,
		Ingredient{item.StoneSlab, 1},
		Ingredient{item.Stick, 6},
	),
	new(item.Chest, 1, Ingredient{item.OakPlanks, 8}),
	new(item.Chest, 1, Ingredient{item.BirchPlanks, 8}),
	new(item.Chest, 1, Ingredient{item.SprucePlanks, 8}),
	new(item.Chest, 1, Ingredient{item.JunglePlanks, 8}),
	new(item.Chest, 1, Ingredient{item.AcaciaPlanks, 8}),
	new(item.Chest, 1, Ingredient{item.DarkOakPlanks, 8}),
	new(item.WhiteStainedGlassPane, 16, Ingredient{item.WhiteStainedGlass, 8}),
	new(item.OrangeStainedGlassPane, 16, Ingredient{item.OrangeStainedGlass, 8}),
	new(item.MagentaStainedGlassPane, 16, Ingredient{item.MagentaStainedGlass, 8}),
	new(item.LightBlueStainedGlassPane, 16, Ingredient{item.LightBlueStainedGlass, 8}),
	new(item.YellowStainedGlassPane, 16, Ingredient{item.YellowStainedGlass, 8}),
	new(item.LimeStainedGlassPane, 16, Ingredient{item.LimeStainedGlass, 8}),
	new(item.PinkStainedGlassPane, 16, Ingredient{item.PinkStainedGlass, 8}),
	new(item.GrayStainedGlassPane, 16, Ingredient{item.GrayStainedGlass, 8}),
	new(item.LightGrayStainedGlassPane, 16, Ingredient{item.LightGrayStainedGlass, 8}),
	new(item.CyanStainedGlassPane, 16, Ingredient{item.CyanStainedGlass, 8}),
	new(item.PurpleStainedGlassPane, 16, Ingredient{item.PurpleStainedGlass, 8}),
	new(item.BlueStainedGlassPane, 16, Ingredient{item.BlueStainedGlass, 8}),
	new(item.BrownStainedGlassPane, 16, Ingredient{item.BrownStainedGlass, 8}),
	new(item.GreenStainedGlassPane, 16, Ingredient{item.GreenStainedGlass, 8}),
	new(item.RedStainedGlassPane, 16, Ingredient{item.RedStainedGlass, 8}),
	new(item.BlackStainedGlassPane, 16, Ingredient{item.BlackStainedGlass, 8}),
	new(item.RedstoneBlock, 1, Ingredient{item.RedstoneWire, 9}),
	new(item.OakDoor, 3, Ingredient{item.OakPlanks, 6}),
	new(item.BirchDoor, 3, Ingredient{item.BirchPlanks, 6}),
	new(item.SpruceDoor, 3, Ingredient{item.SprucePlanks, 6}),
	new(item.JungleDoor, 3, Ingredient{item.JunglePlanks, 6}),
	new(item.AcaciaDoor, 3, Ingredient{item.AcaciaPlanks, 6}),
	new(item.DarkOakDoor, 3, Ingredient{item.DarkOakPlanks, 6}),
	new(item.IronDoor, 3, Ingredient{item.IronIngot, 6}),
	new(item.OakFenceGate, 1,
		Ingredient{item.OakPlanks, 2},
		Ingredient{item.Stick, 4},
	),
	new(item.BirchFenceGate, 3,
		Ingredient{item.BirchPlanks, 2},
		Ingredient{item.Stick, 4},
	),
	new(item.SpruceFenceGate, 3,
		Ingredient{item.SprucePlanks, 2},
		Ingredient{item.Stick, 4},
	),
	new(item.JungleFenceGate, 3,
		Ingredient{item.JunglePlanks, 2},
		Ingredient{item.Stick, 4},
	),
	new(item.AcaciaFenceGate, 3,
		Ingredient{item.AcaciaPlanks, 2},
		Ingredient{item.Stick, 4},
	),
	new(item.DarkOakFenceGate, 3,
		Ingredient{item.DarkOakPlanks, 2},
		Ingredient{item.Stick, 4},
	),
	new(item.Hopper, 1,
		Ingredient{item.Chest, 1},
		Ingredient{item.IronIngot, 5},
	),
	new(item.Lever, 1,
		Ingredient{item.Stick, 1},
		Ingredient{item.Cobblestone, 1},
	),
	new(item.NoteBlock, 1,
		Ingredient{item.OakPlanks, 8},
		Ingredient{item.RedstoneWire, 1},
	),
	new(item.NoteBlock, 1,
		Ingredient{item.BirchPlanks, 8},
		Ingredient{item.RedstoneWire, 1},
	),
	new(item.NoteBlock, 1,
		Ingredient{item.SprucePlanks, 8},
		Ingredient{item.RedstoneWire, 1},
	),
	new(item.NoteBlock, 1,
		Ingredient{item.JunglePlanks, 8},
		Ingredient{item.RedstoneWire, 1},
	),
	new(item.NoteBlock, 1,
		Ingredient{item.AcaciaPlanks, 8},
		Ingredient{item.RedstoneWire, 1},
	),
	new(item.NoteBlock, 1,
		Ingredient{item.DarkOakPlanks, 8},
		Ingredient{item.RedstoneWire, 1},
	),
	new(item.RedstoneWire, 9, Ingredient{item.RedstoneBlock, 1}),
	new(item.WoodTrapdoor, 2, Ingredient{item.OakPlanks, 6}),
	new(item.WoodTrapdoor, 2, Ingredient{item.BirchPlanks, 6}),
	new(item.WoodTrapdoor, 2, Ingredient{item.SprucePlanks, 6}),
	new(item.WoodTrapdoor, 2, Ingredient{item.JunglePlanks, 6}),
	new(item.WoodTrapdoor, 2, Ingredient{item.AcaciaPlanks, 6}),
	new(item.WoodTrapdoor, 2, Ingredient{item.DarkOakPlanks, 6}),
	new(item.IronTrapdoor, 1, Ingredient{item.IronIngot, 4}),
	new(item.TNT, 1, Ingredient{item.Gunpowder, 4}, Ingredient{item.Sand, 4}),
	new(item.TNT, 1,
		Ingredient{item.Gunpowder, 4},
		Ingredient{item.RedSand, 4},
	),
	new(item.DaylightSensor, 1,
		Ingredient{item.Glass, 3},
		Ingredient{item.NetherQuartz, 3},
		Ingredient{item.OakSlab, 3},
	),
	new(item.DaylightSensor, 1,
		Ingredient{item.Glass, 3},
		Ingredient{item.NetherQuartz, 3},
		Ingredient{item.BirchSlab, 3},
	),
	new(item.DaylightSensor, 1,
		Ingredient{item.Glass, 3},
		Ingredient{item.NetherQuartz, 3},
		Ingredient{item.SpruceSlab, 3},
	),
	new(item.DaylightSensor, 1,
		Ingredient{item.Glass, 3},
		Ingredient{item.NetherQuartz, 3},
		Ingredient{item.JungleSlab, 3},
	),
	new(item.DaylightSensor, 1,
		Ingredient{item.Glass, 3},
		Ingredient{item.NetherQuartz, 3},
		Ingredient{item.AcaciaSlab, 3},
	),
	new(item.DaylightSensor, 1,
		Ingredient{item.Glass, 3},
		Ingredient{item.NetherQuartz, 3},
		Ingredient{item.DarkOakSlab, 3},
	),
	new(item.RedstoneRepeater, 1,
		Ingredient{item.Torch, 2},
		Ingredient{item.RedstoneWire, 1},
		Ingredient{item.Stone, 3},
	),
	new(item.WeightedPressurePlateHeavy, 1, Ingredient{item.IronIngot, 2}),
	new(item.WeightedPressurePlateLight, 1, Ingredient{item.GoldIngot, 2}),
	new(item.Dropper, 1,
		Ingredient{item.Cobblestone, 7},
		Ingredient{item.RedstoneWire, 1},
	),
	new(item.RedstoneComparator, 1,
		Ingredient{item.Stone, 3},
		Ingredient{item.RedstoneTorch, 3},
		Ingredient{item.NetherQuartz, 1},
	),
	new(item.StoneButton, 1, Ingredient{item.Stone, 1}),
	new(item.WoodButton, 1, Ingredient{item.OakPlanks, 1}),
	new(item.WoodButton, 1, Ingredient{item.BirchPlanks, 1}),
	new(item.WoodButton, 1, Ingredient{item.SprucePlanks, 1}),
	new(item.WoodButton, 1, Ingredient{item.JunglePlanks, 1}),
	new(item.WoodButton, 1, Ingredient{item.AcaciaPlanks, 1}),
	new(item.WoodButton, 1, Ingredient{item.DarkOakPlanks, 1}),
	new(item.StonePressurePlate, 1, Ingredient{item.Stone, 2}),
	new(item.WoodPressurePlate, 1, Ingredient{item.OakPlanks, 2}),
	new(item.WoodPressurePlate, 1, Ingredient{item.BirchPlanks, 2}),
	new(item.WoodPressurePlate, 1, Ingredient{item.SprucePlanks, 2}),
	new(item.WoodPressurePlate, 1, Ingredient{item.JunglePlanks, 2}),
	new(item.WoodPressurePlate, 1, Ingredient{item.AcaciaPlanks, 2}),
	new(item.WoodPressurePlate, 1, Ingredient{item.DarkOakPlanks, 2}),
	new(item.Piston, 1,
		Ingredient{item.OakPlanks, 3},
		Ingredient{item.Cobblestone, 4},
		Ingredient{item.RedstoneWire, 1},
		Ingredient{item.IronIngot, 1},
	),
	new(item.Piston, 1,
		Ingredient{item.BirchPlanks, 3},
		Ingredient{item.Cobblestone, 4},
		Ingredient{item.RedstoneWire, 1},
		Ingredient{item.IronIngot, 1},
	),
	new(item.Piston, 1,
		Ingredient{item.SprucePlanks, 3},
		Ingredient{item.Cobblestone, 4},
		Ingredient{item.RedstoneWire, 1},
		Ingredient{item.IronIngot, 1},
	),
	new(item.Piston, 1,
		Ingredient{item.JunglePlanks, 3},
		Ingredient{item.Cobblestone, 4},
		Ingredient{item.RedstoneWire, 1},
		Ingredient{item.IronIngot, 1},
	),
	new(item.Piston, 1,
		Ingredient{item.AcaciaPlanks, 3},
		Ingredient{item.Cobblestone, 4},
		Ingredient{item.RedstoneWire, 1},
		Ingredient{item.IronIngot, 1},
	),
	new(item.Piston, 1,
		Ingredient{item.DarkOakPlanks, 3},
		Ingredient{item.Cobblestone, 4},
		Ingredient{item.RedstoneWire, 1},
		Ingredient{item.IronIngot, 1},
	),
	new(item.StickyPiston, 1,
		Ingredient{item.Piston, 1},
		Ingredient{item.Slimeball, 1},
	),
	new(item.RedstoneTorch, 1,
		Ingredient{item.RedstoneWire, 1},
		Ingredient{item.Stick, 1},
	),
	new(item.TripwireHook, 2,
		Ingredient{item.IronIngot, 1},
		Ingredient{item.Stick, 1},
		Ingredient{item.OakPlanks, 1},
	),
	new(item.TripwireHook, 2,
		Ingredient{item.IronIngot, 1},
		Ingredient{item.Stick, 1},
		Ingredient{item.BirchPlanks, 1},
	),
	new(item.TripwireHook, 2,
		Ingredient{item.IronIngot, 1},
		Ingredient{item.Stick, 1},
		Ingredient{item.SprucePlanks, 1},
	),
	new(item.TripwireHook, 2,
		Ingredient{item.IronIngot, 1},
		Ingredient{item.Stick, 1},
		Ingredient{item.JunglePlanks, 1},
	),
	new(item.TripwireHook, 2,
		Ingredient{item.IronIngot, 1},
		Ingredient{item.Stick, 1},
		Ingredient{item.AcaciaPlanks, 1},
	),
	new(item.TripwireHook, 2,
		Ingredient{item.IronIngot, 1},
		Ingredient{item.Stick, 1},
		Ingredient{item.DarkOakPlanks, 1},
	),
	new(item.Dispenser, 1,
		Ingredient{item.Cobblestone, 7},
		Ingredient{item.Bow, 1},
		Ingredient{item.RedstoneWire, 1},
	),
	new(item.RedstoneLamp, 1,
		Ingredient{item.Glowstone, 1},
		Ingredient{item.RedstoneWire, 4},
	),
	new(item.RailActivator, 6,
		Ingredient{item.IronIngot, 6},
		Ingredient{item.RedstoneTorch, 1},
		Ingredient{item.Stick, 2},
	),
	new(item.CarrotOnAStick, 1,
		Ingredient{item.FishingRod, 1},
		Ingredient{item.Carrot, 1},
	),
	new(item.Minecart, 1, Ingredient{item.IronIngot, 5}),
	new(item.MinecartStorage, 1,
		Ingredient{item.Minecart, 1},
		Ingredient{item.Chest, 1},
	),
	new(item.MinecartPowered, 1,
		Ingredient{item.Minecart, 1},
		Ingredient{item.Furnace, 1},
	),
	new(item.MinecartTNT, 1,
		Ingredient{item.Minecart, 1},
		Ingredient{item.TNT, 1},
	),
	new(item.Rail, 16,
		Ingredient{item.IronIngot, 6},
		Ingredient{item.Stick, 1},
	),
	new(item.MinecartHopper, 1,
		Ingredient{item.Minecart, 6},
		Ingredient{item.Hopper, 1},
	),
	new(item.RailPowered, 1,
		Ingredient{item.GoldIngot, 6},
		Ingredient{item.Stick, 1},
		Ingredient{item.RedstoneWire, 1},
	),
	new(item.RailDetector, 1,
		Ingredient{item.IronIngot, 6},
		Ingredient{item.StonePressurePlate, 1},
		Ingredient{item.RedstoneWire, 1},
	),
	new(item.Boat, 1, Ingredient{item.OakPlanks, 4}),
	new(item.Boat, 1, Ingredient{item.BirchPlanks, 4}),
	new(item.Boat, 1, Ingredient{item.SprucePlanks, 4}),
	new(item.Boat, 1, Ingredient{item.JunglePlanks, 4}),
	new(item.Boat, 1, Ingredient{item.AcaciaPlanks, 4}),
	new(item.Boat, 1, Ingredient{item.DarkOakPlanks, 4}),
	new(item.MushroomStew, 1,
		Ingredient{item.MushroomRed, 1},
		Ingredient{item.MushroomBrown, 1},
		Ingredient{item.Bowl, 1},
	),
	new(item.Bread, 1, Ingredient{item.Wheat, 3}),
	new(item.GoldenApple, 1,
		Ingredient{item.GoldIngot, 8},
		Ingredient{item.Apple, 1},
	),
	new(item.EnchantedGoldenApple, 1,
		Ingredient{item.GoldBlock, 8},
		Ingredient{item.Apple, 1},
	),
	new(item.Cookie, 8,
		Ingredient{item.Wheat, 2},
		Ingredient{item.CocoaBean, 1},
	),
	new(item.PumpkinPie, 1,
		Ingredient{item.Pumpkin, 1},
		Ingredient{item.Sugar, 1},
		Ingredient{item.Egg, 1},
	),
	new(item.GoldenCarrot, 1,
		Ingredient{item.Carrot, 1},
		Ingredient{item.GoldNugget, 8},
	),
	new(item.RabbitStew, 1,
		Ingredient{item.Carrot, 1},
		Ingredient{item.Bowl, 1},
		Ingredient{item.RabbitCooked, 1},
		Ingredient{item.PotatoBaked, 1},
	),
	new(item.Cake, 1,
		Ingredient{item.BucketMilk, 3},
		Ingredient{item.Egg, 1},
		Ingredient{item.Sugar, 2},
		Ingredient{item.Wheat, 3},
	),
	new(item.Watch, 1,
		Ingredient{item.GoldIngot, 4},
		Ingredient{item.RedstoneWire, 1},
	),
	new(item.Compass, 1,
		Ingredient{item.IronIngot, 4},
		Ingredient{item.RedstoneWire, 1},
	),
	new(item.FishingRod, 1,
		Ingredient{item.Stick, 3},
		Ingredient{item.String, 2},
	),
	new(item.FlintAndSteel, 1,
		Ingredient{item.IronIngot, 1},
		Ingredient{item.Flint, 1},
	),
	new(item.WoodHoe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.OakPlanks, 2},
	),
	new(item.WoodHoe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.BirchPlanks, 2},
	),
	new(item.WoodHoe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.SprucePlanks, 2},
	),
	new(item.WoodHoe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.JunglePlanks, 2},
	),
	new(item.WoodHoe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.AcaciaPlanks, 2},
	),
	new(item.WoodHoe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.DarkOakPlanks, 2},
	),
	new(item.IronHoe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.IronIngot, 2},
	),
	new(item.GoldHoe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.GoldIngot, 2},
	),
	new(item.DiamondHoe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.Diamond, 2},
	),
	new(item.StoneHoe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.Cobblestone, 2},
	),
	new(item.Lead, 2,
		Ingredient{item.String, 4},
		Ingredient{item.Slimeball, 1},
	),
	new(item.WoodAxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.OakPlanks, 3},
	),
	new(item.WoodAxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.BirchPlanks, 3},
	),
	new(item.WoodAxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.SprucePlanks, 3},
	),
	new(item.WoodAxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.JunglePlanks, 3},
	),
	new(item.WoodAxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.AcaciaPlanks, 3},
	),
	new(item.WoodAxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.DarkOakPlanks, 3},
	),
	new(item.IronAxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.IronIngot, 3},
	),
	new(item.GoldAxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.GoldIngot, 3},
	),
	new(item.DiamondAxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.Diamond, 3},
	),
	new(item.StoneAxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.Cobblestone, 3},
	),
	new(item.WoodPickaxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.OakPlanks, 3},
	),
	new(item.WoodPickaxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.BirchPlanks, 3},
	),
	new(item.WoodPickaxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.SprucePlanks, 3},
	),
	new(item.WoodPickaxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.JunglePlanks, 3},
	),
	new(item.WoodPickaxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.AcaciaPlanks, 3},
	),
	new(item.WoodPickaxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.DarkOakPlanks, 3},
	),
	new(item.IronPickaxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.IronIngot, 3},
	),
	new(item.GoldPickaxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.GoldIngot, 3},
	),
	new(item.DiamondPickaxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.Diamond, 3},
	),
	new(item.StonePickaxe, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.Cobblestone, 3},
	),
	new(item.Shears, 1, Ingredient{item.IronIngot, 2}),
	new(item.WoodShovel, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.OakPlanks, 1},
	),
	new(item.WoodShovel, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.BirchPlanks, 1},
	),
	new(item.WoodShovel, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.SprucePlanks, 1},
	),
	new(item.WoodShovel, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.JunglePlanks, 1},
	),
	new(item.WoodShovel, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.AcaciaPlanks, 1},
	),
	new(item.WoodShovel, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.DarkOakPlanks, 1},
	),
	new(item.IronShovel, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.IronIngot, 1},
	),
	new(item.GoldShovel, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.GoldIngot, 1},
	),
	new(item.DiamondShovel, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.Diamond, 1},
	),
	new(item.StoneShovel, 1,
		Ingredient{item.Stick, 2},
		Ingredient{item.Cobblestone, 1},
	),
	new(item.Bow, 1,
		Ingredient{item.String, 3},
		Ingredient{item.Stick, 3},
	),
	new(item.Arrow, 4,
		Ingredient{item.Flint, 1},
		Ingredient{item.Stick, 1},
		Ingredient{item.Feather, 1},
	),
	new(item.LeatherLeggings, 1, Ingredient{item.Leather, 7}),
	new(item.IronLeggings, 1, Ingredient{item.IronIngot, 7}),
	new(item.GoldLeggings, 1, Ingredient{item.GoldIngot, 7}),
	new(item.DiamondLeggings, 1, Ingredient{item.Diamond, 7}),
	new(item.LeatherBoots, 1, Ingredient{item.Leather, 4}),
	new(item.IronBoots, 1, Ingredient{item.IronIngot, 4}),
	new(item.GoldBoots, 1, Ingredient{item.GoldIngot, 4}),
	new(item.DiamondBoots, 1, Ingredient{item.Diamond, 4}),
	new(item.LeatherHelmet, 1, Ingredient{item.Leather, 5}),
	new(item.IronHelmet, 1, Ingredient{item.IronIngot, 5}),
	new(item.GoldHelmet, 1, Ingredient{item.GoldIngot, 5}),
	new(item.DiamondHelmet, 1, Ingredient{item.Diamond, 5}),
	new(item.LeatherChestplate, 1, Ingredient{item.Leather, 8}),
	new(item.IronChestplate, 1, Ingredient{item.IronIngot, 8}),
	new(item.GoldChestplate, 1, Ingredient{item.GoldIngot, 8}),
	new(item.DiamondChestplate, 1, Ingredient{item.Diamond, 8}),
	new(item.WoodSword, 1,
		Ingredient{item.Stick, 1},
		Ingredient{item.OakPlanks, 2},
	),
	new(item.WoodSword, 1,
		Ingredient{item.Stick, 1},
		Ingredient{item.BirchPlanks, 2},
	),
	new(item.WoodSword, 1,
		Ingredient{item.Stick, 1},
		Ingredient{item.SprucePlanks, 2},
	),
	new(item.WoodSword, 1,
		Ingredient{item.Stick, 1},
		Ingredient{item.JunglePlanks, 2},
	),
	new(item.WoodSword, 1,
		Ingredient{item.Stick, 1},
		Ingredient{item.AcaciaPlanks, 2},
	),
	new(item.WoodSword, 1,
		Ingredient{item.Stick, 1},
		Ingredient{item.DarkOakPlanks, 2},
	),
	new(item.IronSword, 1,
		Ingredient{item.Stick, 1},
		Ingredient{item.IronIngot, 2},
	),
	new(item.GoldSword, 1,
		Ingredient{item.Stick, 1},
		Ingredient{item.GoldIngot, 2},
	),
	new(item.DiamondSword, 1,
		Ingredient{item.Stick, 1},
		Ingredient{item.Diamond, 2},
	),
	new(item.StoneSword, 1,
		Ingredient{item.Stick, 1},
		Ingredient{item.Cobblestone, 2},
	),
	new(item.BlazePowder, 2, Ingredient{item.BlazeRod, 1}),
	new(item.FermentedSpiderEye, 1,
		Ingredient{item.Sugar, 1},
		Ingredient{item.SpiderEye, 1},
		Ingredient{item.MushroomBrown, 1},
	),
	new(item.GlassBottle, 3, Ingredient{item.Glass, 3}),
	new(item.GlisteringMelonSlice, 1,
		Ingredient{item.MelonSlice, 1},
		Ingredient{item.GoldNugget, 8},
	),
	new(item.MagmaCream, 1,
		Ingredient{item.BlazePowder, 1},
		Ingredient{item.Slimeball, 1},
	),
	new(item.BrewingStand, 1,
		Ingredient{item.BlazeRod, 1},
		Ingredient{item.Cobblestone, 3},
	),
	new(item.Cauldron, 3, Ingredient{item.IronIngot, 7}),
	new(item.Bonemeal, 3, Ingredient{item.Bone, 1}),
	new(item.Bowl, 4, Ingredient{item.OakPlanks, 3}),
	new(item.Bowl, 4, Ingredient{item.BirchPlanks, 3}),
	new(item.Bowl, 4, Ingredient{item.SprucePlanks, 3}),
	new(item.Bowl, 4, Ingredient{item.JunglePlanks, 3}),
	new(item.Bowl, 4, Ingredient{item.AcaciaPlanks, 3}),
	new(item.Bowl, 4, Ingredient{item.DarkOakPlanks, 3}),
	new(item.Coal, 9, Ingredient{item.CoalBlock, 1}),
	new(item.CyanDye, 2,
		Ingredient{item.LapisLazuli, 1},
		Ingredient{item.GreenDye, 1},
	),
	new(item.GoldBlock, 1, Ingredient{item.GoldIngot, 9}),
	new(item.GoldIngot, 1, Ingredient{item.GoldNugget, 9}),
	new(item.GoldNugget, 9, Ingredient{item.GoldIngot, 1}),
	new(item.GrayDye, 2,
		Ingredient{item.InkSac, 1},
		Ingredient{item.Bonemeal, 1},
	),
	new(item.IronBlock, 1, Ingredient{item.IronIngot, 9}),
	new(item.LapisLazuliBlock, 1, Ingredient{item.LapisLazuli, 9}),
	new(item.LightBlueDye, 1, Ingredient{item.BlueOrchid, 1}),
	new(item.LightBlueDye, 2,
		Ingredient{item.LapisLazuli, 1},
		Ingredient{item.Bonemeal, 1},
	),
	new(item.LightGrayDye, 1, Ingredient{item.AzureBluet, 1}),
	new(item.LightGrayDye, 1, Ingredient{item.OxeyeDaisy, 1}),
	new(item.LightGrayDye, 1, Ingredient{item.WhiteTulip, 1}),
	new(item.LightGrayDye, 3,
		Ingredient{item.InkSac, 1},
		Ingredient{item.Bonemeal, 2},
	),
	new(item.LightGrayDye, 2,
		Ingredient{item.GrayDye, 1},
		Ingredient{item.Bonemeal, 1},
	),
	new(item.LimeDye, 2,
		Ingredient{item.GreenDye, 1},
		Ingredient{item.Bonemeal, 1},
	),
	new(item.MagentaDye, 2, Ingredient{item.Lilac, 1}),
	new(item.MagentaDye, 1, Ingredient{item.Allium, 1}),
	new(item.MagentaDye, 2,
		Ingredient{item.PurpleDye, 1},
		Ingredient{item.PinkDye, 1},
	),
	new(item.MagentaDye, 4,
		Ingredient{item.LapisLazuli, 1},
		Ingredient{item.Bonemeal, 1},
		Ingredient{item.RedDye, 2},
	),
	new(item.MagentaDye, 3,
		Ingredient{item.PinkDye, 1},
		Ingredient{item.LapisLazuli, 1},
		Ingredient{item.RedDye, 1},
	),
	new(item.OrangeDye, 1, Ingredient{item.OrangeTulip, 1}),
	new(item.OrangeDye, 2,
		Ingredient{item.RedDye, 1},
		Ingredient{item.YellowDye, 1},
	),
	new(item.PinkDye, 1, Ingredient{item.PinkTulip, 1}),
	new(item.PinkDye, 2, Ingredient{item.Peony, 1}),
	new(item.PinkDye, 2,
		Ingredient{item.RedDye, 1},
		Ingredient{item.Bonemeal, 1},
	),
	new(item.PurpleDye, 2,
		Ingredient{item.RedDye, 1},
		Ingredient{item.LapisLazuli, 1},
	),
	new(item.RedDye, 1, Ingredient{item.RedTulip, 1}),
	new(item.RedDye, 2, Ingredient{item.Rosebush, 1}),
	new(item.Stick, 4, Ingredient{item.OakPlanks, 2}),
	new(item.Stick, 4, Ingredient{item.BirchPlanks, 2}),
	new(item.Stick, 4, Ingredient{item.SprucePlanks, 2}),
	new(item.Stick, 4, Ingredient{item.JunglePlanks, 2}),
	new(item.Stick, 4, Ingredient{item.AcaciaPlanks, 2}),
	new(item.Stick, 4, Ingredient{item.DarkOakPlanks, 2}),
	new(item.Sugar, 1, Ingredient{item.Sugarcane, 1}),
	new(item.Wheat, 9, Ingredient{item.HayBale, 1}),
	new(item.YellowDye, 1, Ingredient{item.Dandelion, 1}),
	new(item.YellowDye, 2, Ingredient{item.Sunflower, 1}),
	new(item.Diamond, 9, Ingredient{item.DiamondBlock, 1}),
	new(item.Leather, 1, Ingredient{item.RabbitHide, 4}),
	new(item.Emerald, 9, Ingredient{item.EmeraldBlock, 1}),
	new(item.PumpkinSeeds, 4, Ingredient{item.Pumpkin, 1}),
	new(item.MelonSeeds, 1, Ingredient{item.MelonSlice, 1}),
	new(item.Paper, 3, Ingredient{item.Sugarcane, 3}),
	new(item.Book, 1,
		Ingredient{item.Paper, 3},
		Ingredient{item.Leather, 1},
	),
	new(item.Slimeball, 9, Ingredient{item.SlimeBlock, 1}),
	new(item.FireCharge, 3,
		Ingredient{item.BlazePowder, 1},
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.Coal, 1},
	),
	new(item.FireCharge, 3,
		Ingredient{item.BlazePowder, 1},
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.Charcoal, 1},
	),
	new(item.BookAndQuill, 1,
		Ingredient{item.Book, 1},
		Ingredient{item.Feather, 1},
		Ingredient{item.InkSac, 1},
	),
	new(item.EmptyMap, 1,
		Ingredient{item.Compass, 1},
		Ingredient{item.Paper, 8},
	),
	new(item.Map, 1,
		Ingredient{item.Map, 1},
		Ingredient{item.Paper, 8},
	),
	new(item.Map, 2,
		Ingredient{item.Map, 1},
		Ingredient{item.EmptyMap, 1},
	),
	new(item.Map, 3,
		Ingredient{item.Map, 1},
		Ingredient{item.EmptyMap, 2},
	),
	new(item.Map, 4,
		Ingredient{item.Map, 1},
		Ingredient{item.EmptyMap, 3},
	),
	new(item.Map, 5,
		Ingredient{item.Map, 1},
		Ingredient{item.EmptyMap, 4},
	),
	new(item.Map, 6,
		Ingredient{item.Map, 1},
		Ingredient{item.EmptyMap, 5},
	),
	new(item.Map, 7,
		Ingredient{item.Map, 1},
		Ingredient{item.EmptyMap, 6},
	),
	new(item.Map, 8,
		Ingredient{item.Map, 1},
		Ingredient{item.EmptyMap, 7},
	),
	new(item.Map, 9,
		Ingredient{item.Map, 1},
		Ingredient{item.EmptyMap, 8},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.InkSac, 1},
		Ingredient{item.HeadSkeleton, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.InkSac, 1},
		Ingredient{item.HeadWither, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.InkSac, 1},
		Ingredient{item.HeadZombie, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.InkSac, 1},
		Ingredient{item.HeadSteve, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.InkSac, 1},
		Ingredient{item.HeadCreeper, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.InkSac, 1},
		Ingredient{item.GoldNugget, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.InkSac, 1},
		Ingredient{item.Diamond, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.InkSac, 1},
		Ingredient{item.FireCharge, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.InkSac, 1},
		Ingredient{item.Feather, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.RedDye, 1},
		Ingredient{item.HeadSkeleton, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.RedDye, 1},
		Ingredient{item.HeadWither, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.RedDye, 1},
		Ingredient{item.HeadZombie, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.RedDye, 1},
		Ingredient{item.HeadSteve, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.RedDye, 1},
		Ingredient{item.HeadCreeper, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.RedDye, 1},
		Ingredient{item.GoldNugget, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.RedDye, 1},
		Ingredient{item.Diamond, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.RedDye, 1},
		Ingredient{item.FireCharge, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.RedDye, 1},
		Ingredient{item.Feather, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GreenDye, 1},
		Ingredient{item.HeadSkeleton, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GreenDye, 1},
		Ingredient{item.HeadWither, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GreenDye, 1},
		Ingredient{item.HeadZombie, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GreenDye, 1},
		Ingredient{item.HeadSteve, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GreenDye, 1},
		Ingredient{item.HeadCreeper, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GreenDye, 1},
		Ingredient{item.GoldNugget, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GreenDye, 1},
		Ingredient{item.Diamond, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GreenDye, 1},
		Ingredient{item.FireCharge, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GreenDye, 1},
		Ingredient{item.Feather, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CocoaBean, 1},
		Ingredient{item.HeadSkeleton, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CocoaBean, 1},
		Ingredient{item.HeadWither, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CocoaBean, 1},
		Ingredient{item.HeadZombie, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CocoaBean, 1},
		Ingredient{item.HeadSteve, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CocoaBean, 1},
		Ingredient{item.HeadCreeper, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CocoaBean, 1},
		Ingredient{item.GoldNugget, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CocoaBean, 1},
		Ingredient{item.Diamond, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CocoaBean, 1},
		Ingredient{item.FireCharge, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CocoaBean, 1},
		Ingredient{item.Feather, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LapisLazuli, 1},
		Ingredient{item.HeadSkeleton, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LapisLazuli, 1},
		Ingredient{item.HeadWither, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LapisLazuli, 1},
		Ingredient{item.HeadZombie, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LapisLazuli, 1},
		Ingredient{item.HeadSteve, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LapisLazuli, 1},
		Ingredient{item.HeadCreeper, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LapisLazuli, 1},
		Ingredient{item.GoldNugget, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LapisLazuli, 1},
		Ingredient{item.Diamond, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LapisLazuli, 1},
		Ingredient{item.FireCharge, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LapisLazuli, 1},
		Ingredient{item.Feather, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PurpleDye, 1},
		Ingredient{item.HeadSkeleton, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PurpleDye, 1},
		Ingredient{item.HeadWither, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PurpleDye, 1},
		Ingredient{item.HeadZombie, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PurpleDye, 1},
		Ingredient{item.HeadSteve, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PurpleDye, 1},
		Ingredient{item.HeadCreeper, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PurpleDye, 1},
		Ingredient{item.GoldNugget, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PurpleDye, 1},
		Ingredient{item.Diamond, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PurpleDye, 1},
		Ingredient{item.FireCharge, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PurpleDye, 1},
		Ingredient{item.Feather, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CyanDye, 1},
		Ingredient{item.HeadSkeleton, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CyanDye, 1},
		Ingredient{item.HeadWither, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CyanDye, 1},
		Ingredient{item.HeadZombie, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CyanDye, 1},
		Ingredient{item.HeadSteve, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CyanDye, 1},
		Ingredient{item.HeadCreeper, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CyanDye, 1},
		Ingredient{item.GoldNugget, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CyanDye, 1},
		Ingredient{item.Diamond, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CyanDye, 1},
		Ingredient{item.FireCharge, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CyanDye, 1},
		Ingredient{item.Feather, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightGrayDye, 1},
		Ingredient{item.HeadSkeleton, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightGrayDye, 1},
		Ingredient{item.HeadWither, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightGrayDye, 1},
		Ingredient{item.HeadZombie, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightGrayDye, 1},
		Ingredient{item.HeadSteve, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightGrayDye, 1},
		Ingredient{item.HeadCreeper, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightGrayDye, 1},
		Ingredient{item.GoldNugget, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightGrayDye, 1},
		Ingredient{item.Diamond, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightGrayDye, 1},
		Ingredient{item.FireCharge, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightGrayDye, 1},
		Ingredient{item.Feather, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GrayDye, 1},
		Ingredient{item.HeadSkeleton, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GrayDye, 1},
		Ingredient{item.HeadWither, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GrayDye, 1},
		Ingredient{item.HeadZombie, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GrayDye, 1},
		Ingredient{item.HeadSteve, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GrayDye, 1},
		Ingredient{item.HeadCreeper, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GrayDye, 1},
		Ingredient{item.GoldNugget, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GrayDye, 1},
		Ingredient{item.Diamond, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GrayDye, 1},
		Ingredient{item.FireCharge, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GrayDye, 1},
		Ingredient{item.Feather, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PinkDye, 1},
		Ingredient{item.HeadSkeleton, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PinkDye, 1},
		Ingredient{item.HeadWither, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PinkDye, 1},
		Ingredient{item.HeadZombie, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PinkDye, 1},
		Ingredient{item.HeadSteve, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PinkDye, 1},
		Ingredient{item.HeadCreeper, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PinkDye, 1},
		Ingredient{item.GoldNugget, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PinkDye, 1},
		Ingredient{item.Diamond, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PinkDye, 1},
		Ingredient{item.FireCharge, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PinkDye, 1},
		Ingredient{item.Feather, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LimeDye, 1},
		Ingredient{item.HeadSkeleton, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LimeDye, 1},
		Ingredient{item.HeadWither, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LimeDye, 1},
		Ingredient{item.HeadZombie, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LimeDye, 1},
		Ingredient{item.HeadSteve, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LimeDye, 1},
		Ingredient{item.HeadCreeper, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LimeDye, 1},
		Ingredient{item.GoldNugget, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LimeDye, 1},
		Ingredient{item.Diamond, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LimeDye, 1},
		Ingredient{item.FireCharge, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LimeDye, 1},
		Ingredient{item.Feather, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.YellowDye, 1},
		Ingredient{item.HeadSkeleton, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.YellowDye, 1},
		Ingredient{item.HeadWither, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.YellowDye, 1},
		Ingredient{item.HeadZombie, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.YellowDye, 1},
		Ingredient{item.HeadSteve, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.YellowDye, 1},
		Ingredient{item.HeadCreeper, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.YellowDye, 1},
		Ingredient{item.GoldNugget, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.YellowDye, 1},
		Ingredient{item.Diamond, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.YellowDye, 1},
		Ingredient{item.FireCharge, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.YellowDye, 1},
		Ingredient{item.Feather, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightBlueDye, 1},
		Ingredient{item.HeadSkeleton, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightBlueDye, 1},
		Ingredient{item.HeadWither, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightBlueDye, 1},
		Ingredient{item.HeadZombie, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightBlueDye, 1},
		Ingredient{item.HeadSteve, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightBlueDye, 1},
		Ingredient{item.HeadCreeper, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightBlueDye, 1},
		Ingredient{item.GoldNugget, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightBlueDye, 1},
		Ingredient{item.Diamond, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightBlueDye, 1},
		Ingredient{item.FireCharge, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightBlueDye, 1},
		Ingredient{item.Feather, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.MagentaDye, 1},
		Ingredient{item.HeadSkeleton, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.MagentaDye, 1},
		Ingredient{item.HeadWither, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.MagentaDye, 1},
		Ingredient{item.HeadZombie, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.MagentaDye, 1},
		Ingredient{item.HeadSteve, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.MagentaDye, 1},
		Ingredient{item.HeadCreeper, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.MagentaDye, 1},
		Ingredient{item.GoldNugget, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.MagentaDye, 1},
		Ingredient{item.Diamond, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.MagentaDye, 1},
		Ingredient{item.FireCharge, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.MagentaDye, 1},
		Ingredient{item.Feather, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.OrangeDye, 1},
		Ingredient{item.HeadSkeleton, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.OrangeDye, 1},
		Ingredient{item.HeadWither, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.OrangeDye, 1},
		Ingredient{item.HeadZombie, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.OrangeDye, 1},
		Ingredient{item.HeadSteve, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.OrangeDye, 1},
		Ingredient{item.HeadCreeper, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.OrangeDye, 1},
		Ingredient{item.GoldNugget, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.OrangeDye, 1},
		Ingredient{item.Diamond, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.OrangeDye, 1},
		Ingredient{item.FireCharge, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.OrangeDye, 1},
		Ingredient{item.Feather, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.Bonemeal, 1},
		Ingredient{item.HeadSkeleton, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.Bonemeal, 1},
		Ingredient{item.HeadWither, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.Bonemeal, 1},
		Ingredient{item.HeadZombie, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.Bonemeal, 1},
		Ingredient{item.HeadSteve, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.Bonemeal, 1},
		Ingredient{item.HeadCreeper, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.Bonemeal, 1},
		Ingredient{item.GoldNugget, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.Bonemeal, 1},
		Ingredient{item.Diamond, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.Bonemeal, 1},
		Ingredient{item.FireCharge, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.Bonemeal, 1},
		Ingredient{item.Feather, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.InkSac, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.RedDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GreenDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CocoaBean, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LapisLazuli, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PurpleDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.CyanDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightGrayDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.GrayDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.PinkDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LimeDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.YellowDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.LightBlueDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.MagentaDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.OrangeDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.Bonemeal, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.FireworkStar, 1},
		Ingredient{item.InkSac, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.FireworkStar, 1},
		Ingredient{item.RedDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.FireworkStar, 1},
		Ingredient{item.GreenDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.FireworkStar, 1},
		Ingredient{item.CocoaBean, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.FireworkStar, 1},
		Ingredient{item.LapisLazuli, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.FireworkStar, 1},
		Ingredient{item.PurpleDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.FireworkStar, 1},
		Ingredient{item.CyanDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.FireworkStar, 1},
		Ingredient{item.LightGrayDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.FireworkStar, 1},
		Ingredient{item.GrayDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.FireworkStar, 1},
		Ingredient{item.PinkDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.FireworkStar, 1},
		Ingredient{item.LimeDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.FireworkStar, 1},
		Ingredient{item.YellowDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.FireworkStar, 1},
		Ingredient{item.LightBlueDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.FireworkStar, 1},
		Ingredient{item.MagentaDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.FireworkStar, 1},
		Ingredient{item.OrangeDye, 1},
	),
	new(item.FireworkStar, 1,
		Ingredient{item.FireworkStar, 1},
		Ingredient{item.Bonemeal, 1},
	),
	new(item.FireworkRocket, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.Paper, 1},
	),
	new(item.FireworkRocket, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.Paper, 1},
		Ingredient{item.FireworkStar, 1},
	),
	new(item.FireworkRocket, 1,
		Ingredient{item.Gunpowder, 2},
		Ingredient{item.Paper, 1},
		Ingredient{item.FireworkStar, 1},
	),
	new(item.FireworkRocket, 1,
		Ingredient{item.Gunpowder, 3},
		Ingredient{item.Paper, 1},
		Ingredient{item.FireworkStar, 1},
	),
	new(item.FireworkRocket, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.Paper, 1},
		Ingredient{item.FireworkStar, 2},
	),
	new(item.FireworkRocket, 1,
		Ingredient{item.Gunpowder, 2},
		Ingredient{item.Paper, 1},
		Ingredient{item.FireworkStar, 2},
	),
	new(item.FireworkRocket, 1,
		Ingredient{item.Gunpowder, 3},
		Ingredient{item.Paper, 1},
		Ingredient{item.FireworkStar, 2},
	),
	new(item.FireworkRocket, 1,
		Ingredient{item.Gunpowder, 1},
		Ingredient{item.Paper, 1},
		Ingredient{item.FireworkStar, 3},
	),
	new(item.FireworkRocket, 1,
		Ingredient{item.Gunpowder, 2},
		Ingredient{item.Paper, 1},
		Ingredient{item.FireworkStar, 3},
	),
	new(item.FireworkRocket, 1,
		Ingredient{item.Gunpowder, 3},
		Ingredient{item.Paper, 1},
		Ingredient{item.FireworkStar, 3},
	),
	new(item.WrittenBook, 1,
		Ingredient{item.WrittenBook, 1},
		Ingredient{item.BookAndQuill, 1},
	),
	new(item.WrittenBook, 2,
		Ingredient{item.WrittenBook, 1},
		Ingredient{item.BookAndQuill, 2},
	),
	new(item.WrittenBook, 3,
		Ingredient{item.WrittenBook, 1},
		Ingredient{item.BookAndQuill, 3},
	),
	new(item.WrittenBook, 4,
		Ingredient{item.WrittenBook, 1},
		Ingredient{item.BookAndQuill, 4},
	),
	new(item.WrittenBook, 5,
		Ingredient{item.WrittenBook, 1},
		Ingredient{item.BookAndQuill, 5},
	),
	new(item.WrittenBook, 6,
		Ingredient{item.WrittenBook, 1},
		Ingredient{item.BookAndQuill, 6},
	),
	new(item.WrittenBook, 7,
		Ingredient{item.WrittenBook, 1},
		Ingredient{item.BookAndQuill, 7},
	),
	new(item.WrittenBook, 8,
		Ingredient{item.WrittenBook, 1},
		Ingredient{item.BookAndQuill, 8},
	),
	new(item.Beacon, 1,
		Ingredient{item.Obsidian, 3},
		Ingredient{item.Glass, 4},
		Ingredient{item.NetherStar, 1},
	),
	new(item.Bucket, 1, Ingredient{item.IronIngot, 3}),
	new(item.EyeOfEnder, 1,
		Ingredient{item.EnderPearl, 1},
		Ingredient{item.BlazePowder, 1},
	),
}
